foldersTree = gFld("<b>HPGCCLibrary</b>", "", "")
     insDoc(foldersTree, gLnk("Main Page", "", "main.html"))
aux1 = insFld(foldersTree, gFld("File List", "", "files.html"))
       insDoc(aux1, gLnk("hpconio.h", "", "hpconio_8h.html"))
       insDoc(aux1, gLnk("hpctype.h", "", "hpctype_8h.html"))
       insDoc(aux1, gLnk("hpgcc49.h", "", "hpgcc49_8h.html"))
       insDoc(aux1, gLnk("hpkeyb49.h", "", "hpkeyb49_8h.html"))
       insDoc(aux1, gLnk("hpmath.h", "", "hpmath_8h.html"))
       insDoc(aux1, gLnk("hpscreen.h", "", "hpscreen_8h.html"))
       insDoc(aux1, gLnk("hpstdio.h", "", "hpstdio_8h.html"))
       insDoc(aux1, gLnk("hpstdlib.h", "", "hpstdlib_8h.html"))
       insDoc(aux1, gLnk("hpstring.h", "", "hpstring_8h.html"))
       insDoc(aux1, gLnk("hpsys.h", "", "hpsys_8h.html"))
       insDoc(aux1, gLnk("hptime.h", "", "hptime_8h.html"))
       insDoc(aux1, gLnk("kos.h", "", "kos_8h.html"))
       insDoc(aux1, gLnk("syscall.h", "", "syscall_8h.html"))
aux1 = insFld(foldersTree, gFld("Data Structures", "", "annotated.html"))
       insDoc(aux1, gLnk("FILE", "", "structFILE.html"))
       insDoc(aux1, gLnk("lldiv_t", "", "structlldiv__t.html"))
     insDoc(foldersTree, gLnk("Data Fields", "", "functions.html"))
     insDoc(foldersTree, gLnk("Globals", "", "globals.html"))
